### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by sari777** [unclevito2017/VBCR-stride-w-random#1]
thanks for your program. how can we search for case sensitive.? and why my program starting only with 20000000000000000:21000000000000000 . how to get the random value like you elaborate in the read.me.?
what is stride means.? it skips key of that value.? for example 173753 stride value. it will skip that decimal value or what.?

**Comment by unclevito2017** [comment]
20000000000000000 is the starting keyspace for 66. Yes the stride jumps over  so 173752 would jump that many keys each restart you should have something like this 
Enter the stride value: 500000000000000000
Random Increment: 9b59b567c9
Stride: 500000000000000000
VBCr v2.00
 Search For: 13zb1hQbWVsc [Compressed, Case unsensitive] (Lookup size 4)
 Started on: Sat Aug 19 17:40:50 2023
 Randomness: New Random Keys Every 50000 Mkeys
  Beg Range: 20000009B59B567C9 (66 bit)
  End Range: 200000136B36ACF91 (66 bit)
  Rng Width: 9B59B567C8 (40 bit)      range width 
CPU Threads: 0
GPU: GPU #0 NVIDIA GeForce RTX 3060 Ti (38x128 cores) Grid(304x128)

Random Key :  2000000FF74F514E8
Random Key :  2000000C6B4206FCA
Random Key :  2000000C31BD0212B
Random Key :  2000001175FAFAAD4
Random Key :  2000000DF531BF011
Random Key :  200000134557FCDE3
Random Key :  2000000D00914CBB9
Random Key :  2000000B09C45CBAC
Random Key :  2000000C9ED12C5A1
 [00:00:01:01 Run Time][Total 816.05 MK/s][GPU 816.05 MK/s][Keys 50,524,585,984][Found 0][Rekeys: 0]
you must remember the 66 keyspace is 36 quintillion spaces wide 36893488147419103232 so if you just jump 173753 it will take you 58,981,376,736 almost 59 billion hours  to go through the entire keyspace 66. so you want to use a much larger stride so what we are doing is jumping to points throughout keyspace 66 and looking in the narrow range width  Rng Width: 9B59B567C8 (40 bit) in this example for the correct address. so you have a large stride: I am currently using Stride: 500000000000000000 which will take about 1 hour and 15 minutses to go through the keyspace and a range width of 40  bits. Where you are getting a start of 20000000000000000:21000000000000000 I have no idea because the start in the code  is '20000000000000000', '20010000000000000' are you using VBCR.exe?  to use this python program simply put VBCR.exe in the folder with 66-stride.py open a command prompt and run python3 66-stride.py and the program should start enter your stride value and it should run.  if you want to change the starting keyspace you can change '20000000000000000', '20010000000000000'  to '30000000000000000', '30010000000000000' in the code or whatever address in 66 you want to start at  the one on the right 30010000000000000 has to have a slightly higher value. If you want to change the range width you change the k=value in the code currently 10 to 1 through 15  but the best chance for luck would be k= either 9 10 or 11

**Comment by unclevito2017** [comment]
The program generates a .pkl checkpoint.pkl file that remembers the last space you searched through so if you want to quit for a while the pickle file remembers the last checkpoint just run python3 66-stride.py and the program will resume from where you  left off. if you run for a while and want to try a new starting point  or get to the end of the keyspace you need to delete the checkpoint.pkl or move it out of the folder  or you will be brought back to the last stop point no matter if you change the start point in the code

**Comment by unclevito2017** [comment]
I have uploaded the case sensitive version

**Comment by unclevito2017** [comment]
one last thing when you run the stride depending on the speed of your gpu you are searching in the example above 50 billion locations in the keyspace each time it strides to a new point. if you only are using cpu's it would be less locations searched

**Comment by sari777** [comment]
ok dear thanks for all answers. i will work on it.
great.

**Comment by sari777** [comment]
i have one more question.
how to know that key is really present in that range.? puzzle 66. 20000000000000000:3ffffffffffffffff.
which script or which code can confirm it.?
because the keys which have hit now 120 and 125 in the puzzle, are not displayed on the website.
they said, they did not display the keys due to security reason. what the hell.

**Comment by unclevito2017** [comment]
puzzle 66 you are looking for address 13zb1hQbWVsc2S7ZTZnP2G4undNNpdh5so with this program you are searching the prefix set in the code as 13zb1hQb which can be changed in the code making it longer or shorter. each time the program that finds an address starting with 13zb1hQb it prints out the address and private key to the screen and text file the address and private key found. so you will find many addresses and private keys in 66 starting with 13zb1hQb and hopefully one of them is the one you are looking for 13zb1hQbWVsc2S7ZTZnP2G4undNNpdh5so.

**Comment by sari777** [comment]
you did not understand me, i asked how to confirm that the key for address "13zb1hQbWVsc2S7ZTZnP2G4undNNpdh5so" is really present in the given range "20000000000000000:3ffffffffffffffff" which script can confirm this.

**Comment by sari777** [comment]
and can you make wondering philosopher vbcr.exe program for linux cuda multiple gpu.?

**Comment by unclevito2017** [comment]
There is no program that can confirm that, if you could confirm then you would know where it is. People starting asking the same question for 64 because it took so long to find but it was found as were the last 65 . NO Wandering Philosopher did not publish the source code so it is not possible to make a linux version without the code.

**Comment by sari777** [comment]
ok. right. thanks.
